export const prerender = false

import type { APIRoute } from 'astro'

interface QAEntry {
  category: string
  question: string
  answer: string
  related_product: string
  priority: string
}

const QA: QAEntry[] = [
  // Product Selection
  { category: 'Product Selection', question: 'Which machine should I choose for making stand-up doypack pouches?', answer: 'The JL-L-2TZP600 is the right choice. It produces stand-up doypack pouches — both plain and with zipper — at 35–120 pcs/min, using heat-seal laminated film (30–180 μm). It handles five bag styles on a single platform so you can switch formats without changing machines.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Product Selection', question: 'Can one machine make both flat three-side seal bags and doypack pouches?', answer: 'Yes. The JL-L-2TZP600 is a multi-function platform that produces three-side seal bags, three-side seal zipper bags, four-side seal bags, doypack pouches, and doypack with zipper — all on one machine. Switching between bag styles requires a format changeover but no separate machine.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Product Selection', question: 'I need to produce coffee bags with a degassing valve. Which machine is suitable?', answer: 'The JL-L-2TZP600 supports coffee packaging (both center-seal and doypack formats) and can accommodate degassing valve insertion. Please contact us with your specific valve type and bag dimensions for a configuration confirmation.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Product Selection', question: 'Do you have a machine for PP woven bags?', answer: 'Yes. The JLPTCSM-1300W is a fully integrated convention line for high-volume PP woven bag production, combining flexographic printing, tube forming, cutting & sewing, and overtape application in one continuous process at 25–40 bags/min.', related_product: 'JLPTCSM-1300W', priority: 'H' },
  { category: 'Product Selection', question: 'What machine makes medical packaging bags or sterilization pouches?', answer: 'The JL-L-2TZP600 supports medical packaging applications, including individual bags and flat pouches. For specialized medical bag types such as gusseted tube bags or four-layer header bags, please contact our engineering team with your specifications.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Product Selection', question: 'I need to package pet food. What bag machine do you recommend?', answer: 'The JL-L-2TZP600 handles pet food packaging in doypack, stand-up zipper, and three-side seal formats using high-barrier laminated film. This is a common application — please share your target bag dimensions and production speed for a detailed recommendation.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Product Selection', question: 'Which machine is best for facial mask or cosmetic packaging?', answer: 'The JL-L-2TZP600 produces three-side seal and doypack bags commonly used for facial masks, skincare, and cosmetic products. It supports printed laminated films with ≤0.3 mm positional accuracy for precise register printing alignment.', related_product: 'JL-L-2TZP600', priority: 'M' },
  { category: 'Product Selection', question: 'Can your machines handle anti-static packaging for electronics?', answer: 'Yes. The JL-L-2TZP600 can process anti-static laminated films suitable for electronic component packaging. The applicable film thickness range is 30–180 μm. Please specify your film type so we can confirm compatibility.', related_product: 'JL-L-2TZP600', priority: 'M' },
  // Technical – JL-L-2TZP600
  { category: 'Technical – JL-L-2TZP600', question: 'What is the maximum production speed of the JL-L-2TZP600?', answer: 'The JL-L-2TZP600 runs at up to 220 pcs/min for three-side seal bags, 150 pcs/min for three-side seal with zipper bags, and 120 pcs/min for doypack pouches. Minimum speed is 35 pcs/min across all formats.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Technical – JL-L-2TZP600', question: 'What bag sizes can the JL-L-2TZP600 produce?', answer: 'Bag width ranges from 100 to 580 mm, and bag length from 50 to 420 mm. A skip function extends the effective length up to 6× for longer bags. Bottom seal width is adjustable from 5 to 60 mm.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Technical – JL-L-2TZP600', question: 'What materials can the JL-L-2TZP600 process?', answer: 'The machine is designed for heat-seal laminated films with a thickness of 30–180 μm. Common structures include NY/PE, PET/PE, AL/PE, OPP/CPP, and BOPP/LLDPE. Please confirm your specific film structure for compatibility.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Technical – JL-L-2TZP600', question: 'What power supply does the JL-L-2TZP600 require?', answer: '220 V / 3-phase / 60 Hz, with a total power consumption of 60 kW. If your facility operates at 50 Hz, please inform us — the machine can be configured for 50 Hz with appropriate servo adjustments.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Technical – JL-L-2TZP600', question: 'How precise is the sealing and registration on the JL-L-2TZP600?', answer: 'Positional accuracy is ≤0.3 mm, achieved through full servo-motor control (Panasonic). The sealing system uses 4 groups of heating + 2 groups of cooling for both vertical and horizontal seals, ensuring consistent seal quality.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Technical – JL-L-2TZP600', question: 'How is the zipper sealed on the zipper bag format?', answer: 'Zipper sealing uses ultrasonic technology (1 group), which provides a clean, consistent seal without heat damage to the zipper track. Standard zipper width is 13 mm.', related_product: 'JL-L-2TZP600', priority: 'M' },
  { category: 'Technical – JL-L-2TZP600', question: 'What is the machine weight and footprint of the JL-L-2TZP600?', answer: 'The machine weighs 9,000 kg. Please contact us for the full installation drawing with exact footprint dimensions and recommended clearance space for your facility planning.', related_product: 'JL-L-2TZP600', priority: 'M' },
  { category: 'Technical – JL-L-2TZP600', question: 'What control system does the JL-L-2TZP600 use?', answer: 'The machine uses a PLC touch-screen interface with full servo-motor control (Panasonic servo drives). The 10 mm steel-plate frame provides vibration resistance for high-speed continuous operation.', related_product: 'JL-L-2TZP600', priority: 'M' },
  { category: 'Technical – JL-L-2TZP600', question: 'Can the JL-L-2TZP600 run retort or high-temperature packaging films?', answer: 'Yes. The temperature range reaches up to 300°C, making it suitable for retort packaging films (NY/CPP, AL/CPP retort-grade) used in cooked food and sterilized product packaging.', related_product: 'JL-L-2TZP600', priority: 'M' },
  // Technical – JLPTCSM-1300W
  { category: 'Technical – JLPTCSM-1300W', question: 'What is the production speed of the PP woven bag convention line?', answer: 'The JLPTCSM-1300W produces 25–40 bags/min. It integrates four stages — flexographic printing, tube forming, cutting & sewing, and overtape application — in a single continuous process.', related_product: 'JLPTCSM-1300W', priority: 'H' },
  { category: 'Technical – JLPTCSM-1300W', question: 'What bag dimensions does the JLPTCSM-1300W handle?', answer: 'The line handles fabric widths of 700–1300 mm (before tubing), resulting in finished bag widths of 430–660 mm. Cutting length ranges from 550–1250 mm. Gusset depth is adjustable from 40–90 mm.', related_product: 'JLPTCSM-1300W', priority: 'M' },
  { category: 'Technical – JLPTCSM-1300W', question: 'How many print colors does the woven bag convention line support?', answer: 'The JLPTCSM-1300W supports 4-color flexographic printing (4+0 configuration) with a printing repeat length of 450–1200 mm and max printing width of 1300 mm.', related_product: 'JLPTCSM-1300W', priority: 'M' },
  // Technical – Printing Machine
  { category: 'Technical – Printing Machine', question: 'What materials can the 6-color flexographic printing machine print on?', answer: 'The JLRPM-6800BO/6C is designed for PP woven fabric and PP laminated fabric, with a max web width of 800 mm and max machine speed of 120 m/min (printing speed up to 100 m/min).', related_product: 'JLRPM-6800BO/6C', priority: 'M' },
  { category: 'Technical – Printing Machine', question: 'How many colors can the flexographic printing machine print?', answer: '6 colors, using 6 independent printing stations with ceramic anilox rollers. Configurations supported: 0+6, 1+5, 2+4, 3+3 (front/back). An inter-color drying system ensures clean separation between stations.', related_product: 'JLRPM-6800BO/6C', priority: 'M' },
  // Technical – Recycling
  { category: 'Technical – Recycling', question: 'What materials does the eddy current separator recover?', answer: 'The JLECS-1000W recovers non-ferrous metals (aluminum, copper, brass) from mixed material streams such as e-waste, shredded plastic, and mixed scrap. It combines magnetic drum separation (ferrous removal) with eddy current separation (non-ferrous recovery) at 1,000 kg/h capacity.', related_product: 'JLECS-1000W', priority: 'M' },
  // AI Solutions
  { category: 'AI Solutions', question: 'What is the AI Machine Intelligence solution?', answer: "Rey Long's AI Machine Intelligence embeds edge computing and industrial IoT into existing production lines. It provides real-time decisions at the machine level — including computer vision quality inspection, predictive maintenance, and process optimization — without relying on cloud connectivity.", related_product: 'AI Solutions', priority: 'M' },
  { category: 'AI Solutions', question: 'Can AI be retrofitted onto an existing machine?', answer: 'Yes. The AI program is designed case-by-case for specific machines and processes. It can be integrated into existing production lines without requiring a full machine replacement. Contact us with your machine type and target application for an assessment.', related_product: 'AI Solutions', priority: 'M' },
  // Procurement
  { category: 'Procurement', question: 'How do I get a price quote?', answer: 'Pricing depends on your specific configuration — bag type, dimensions, speed, and options. Use the "Request a Quote" button on any product page or visit our Contact page. Our team responds within 1 business day with a tailored quotation.', related_product: 'All', priority: 'H' },
  { category: 'Procurement', question: 'How much does the JL-L-2TZP600 cost?', answer: 'Machine pricing varies based on configuration, options, and destination. To receive an accurate quote for your requirements, please use the Request a Quote form on the product page — our team will respond within 1 business day.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Procurement', question: 'What is the price of the PP woven bag convention line?', answer: 'Pricing for the JLPTCSM-1300W depends on your production specifications. Please fill in the inquiry form on the product page and our sales team will provide a detailed quotation promptly.', related_product: 'JLPTCSM-1300W', priority: 'H' },
  { category: 'Procurement', question: 'Can you give me a ballpark price or price range?', answer: "We quote based on your exact requirements to ensure the price reflects your configuration accurately. Please submit an inquiry with your target bag type, dimensions, and speed — we'll get back to you within 1 business day with a specific figure.", related_product: 'All', priority: 'H' },
  { category: 'Procurement', question: 'What is the typical lead time for machine delivery?', answer: 'Standard lead time is 2–3 months from order confirmation. This covers manufacturing, quality testing, and pre-shipment inspection. Complex customizations may require additional time — we will confirm the exact schedule at order stage.', related_product: 'All', priority: 'H' },
  { category: 'Procurement', question: 'Do you offer machine customization?', answer: 'Yes. Rey Long offers customization for most machine models — including bag size range, speed configuration, optional accessories, and special film compatibility. Please provide your production requirements and our engineering team will advise on feasibility.', related_product: 'All', priority: 'H' },
  { category: 'Procurement', question: 'What payment terms do you offer?', answer: 'Payment terms are discussed on a per-order basis. Please submit an inquiry and our sales team will include payment options in the quotation response.', related_product: 'All', priority: 'H' },
  { category: 'Procurement', question: 'Do you export to the United States / Japan?', answer: 'Yes. Rey Long supplies machinery to customers in the United States, Japan, and globally. We have experience with export documentation, container loading, and international shipping coordination.', related_product: 'All', priority: 'H' },
  { category: 'Procurement', question: 'What voltage and frequency options are available?', answer: 'Machines are configurable for different power standards. The JL-L-2TZP600 default is 220V/3P/60Hz. 50 Hz configurations are available — please specify your local power standard when requesting a quote.', related_product: 'All', priority: 'H' },
  // After-Sales
  { category: 'After-Sales', question: 'What warranty does Rey Long provide?', answer: 'Rey Long provides warranty coverage on parts and workmanship. Specific warranty terms are stated in the sales contract. Please contact us for details applicable to your machine and region.', related_product: 'All', priority: 'H' },
  { category: 'After-Sales', question: 'Is installation and training included?', answer: 'Yes. Rey Long provides technical documentation, remote support, and on-site installation assistance. Operator training is included as part of the commissioning process.', related_product: 'All', priority: 'H' },
  { category: 'After-Sales', question: 'How do I order spare parts?', answer: 'Spare parts are available globally with fast delivery. Contact our after-sales team with your machine model number and the part specification (or a photo/drawing) for a quick quotation.', related_product: 'All', priority: 'H' },
  { category: 'After-Sales', question: 'Do you provide remote technical support?', answer: 'Yes. Rey Long provides remote support via video call, with real-time guidance from our engineers. For major issues, on-site service can be arranged.', related_product: 'All', priority: 'M' },
  // Company
  { category: 'Company', question: 'Where is Rey Long based?', answer: 'Rey Long Machinery Co., Ltd. is a professional manufacturer of plastic and packaging machinery headquartered in Taiwan, serving manufacturers worldwide.', related_product: 'Company', priority: 'H' },
  { category: 'Company', question: 'What types of machines does Rey Long manufacture?', answer: 'Rey Long manufactures flexible packaging bag making machines (three-side seal, doypack, zipper), PP woven bag convention lines, flexographic printing machines, recycling separation systems, and AI-powered machine intelligence solutions.', related_product: 'Company', priority: 'H' },
  { category: 'Company', question: 'Does Rey Long have CE certification or international certifications?', answer: 'CE certification for our machines is currently in progress. We will provide updated certification documentation as it becomes available. Please contact us for the latest status relevant to your target market.', related_product: 'Company', priority: 'M' },
  // Application
  { category: 'Application', question: 'Can the JL-L-2TZP600 produce liquid packaging pouches?', answer: 'Yes. The JL-L-2TZP600 supports liquid packaging in doypack and three-side seal formats using appropriate barrier laminated films. For liquid-fill integration, the bag is typically made on the JL-L-2TZP600 and filled on a separate filling machine.', related_product: 'JL-L-2TZP600', priority: 'M' },
  { category: 'Application', question: 'Is the machine suitable for rice or grain packaging?', answer: 'Yes. The JL-L-2TZP600 handles rice packaging in three-side seal and doypack formats. Film thickness up to 180 μm accommodates the heavier-gauge films often used for grain packaging.', related_product: 'JL-L-2TZP600', priority: 'M' },
  { category: 'Application', question: 'Can I use the machine for garment or clothing packaging?', answer: 'Yes. Three-side seal bags and doypack pouches produced by the JL-L-2TZP600 are used for garment packaging. The machine supports wide bags (up to 580 mm) suitable for folded clothing.', related_product: 'JL-L-2TZP600', priority: 'M' },
  { category: 'Application', question: 'What frozen food packaging can this machine produce?', answer: 'The JL-L-2TZP600 produces frozen food packaging in three-side seal, doypack, and zipper formats using NY/PE or PET/PE laminated films rated for freezer temperatures. The sealing temperature range (up to 300°C) handles the full range of freeze-grade films.', related_product: 'JL-L-2TZP600', priority: 'M' },
  // Comparison
  { category: 'Comparison', question: 'How does the JL-L-2TZP600 compare to other high-speed pouch machines on the market?', answer: 'The JL-L-2TZP600 delivers ≤0.3 mm positional accuracy and up to 220 pcs/min using Panasonic full-servo control — performance comparable to premium international machines, with competitive pricing and a 2–3 month lead time. The 10 mm steel-plate frame provides superior rigidity at high speed.', related_product: 'JL-L-2TZP600', priority: 'M' },
  { category: 'Comparison', question: 'What makes Rey Long machines different from other manufacturers?', answer: 'Key differentiators: 10 mm steel-plate frame (heavier than industry standard) for vibration resistance, full Panasonic servo control, multi-format capability on a single platform, AI integration options, and direct factory engineering support. Lead time is 2–3 months.', related_product: 'All', priority: 'M' },
  // Technical – Operations
  { category: 'Technical – Operations', question: 'How long does it take to change over between bag formats on the JL-L-2TZP600?', answer: 'Format changeover time depends on the degree of size change. Minor adjustments (same format, different size) typically take 15–30 minutes. Switching between bag types (e.g., three-side seal to doypack) may take 30–60 minutes with trained operators. Rey Long provides changeover procedures and operator training during commissioning.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Technical – Operations', question: 'How do I set the sealing temperature for a new film material?', answer: "Sealing temperature is set via the PLC touch screen. Start with the film supplier's recommended heat-seal temperature range, then run test bags at low speed and adjust in 5°C increments until seal quality is consistent. The machine supports up to 300°C. Rey Long's commissioning engineer will demonstrate this process during installation.", related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Technical – Operations', question: 'What causes poor seal quality or seal leakage?', answer: 'Common causes: (1) sealing temperature too low for the film material, (2) sealing pressure insufficient, (3) sealing dwell time too short at high speed, (4) film contamination or moisture on the seal area, (5) worn sealing bar. Check temperature settings first, then inspect the sealing bar surface. Contact our technical support team if the issue persists.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Technical – Operations', question: 'What causes misaligned printing registration on finished bags?', answer: 'Registration errors are typically caused by: (1) inconsistent film tension — check the tension control setting, (2) film splice or quality variation, (3) photo-eye sensor sensitivity needs adjustment, (4) servo parameters need recalibration. The JL-L-2TZP600 has ≤0.3 mm accuracy under normal operating conditions. Contact Rey Long technical support for sensor and servo calibration guidance.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Technical – Operations', question: 'How do I thread the film into the machine?', answer: "Film threading procedure is detailed in the operation manual provided with the machine. Rey Long's commissioning engineer demonstrates threading during installation and training. A threading diagram is also posted near the film path on the machine for reference.", related_product: 'JL-L-2TZP600', priority: 'M' },
  { category: 'Technical – Operations', question: 'What is the recommended maintenance schedule for the JL-L-2TZP600?', answer: 'Recommended schedule: Daily — clean sealing bars, check film path and tension rollers. Weekly — lubricate moving parts per the lubrication chart, inspect servo belts. Monthly — check electrical connections, inspect heating elements and thermocouples. A full maintenance checklist is included in the operation manual. Rey Long also offers remote maintenance support.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Technical – Operations', question: 'What spare parts should I keep in stock?', answer: 'Recommended stock items: sealing bars (vertical and horizontal), silicone pads, heating elements, thermocouples, photo-eye sensors, and servo belts. Rey Long provides a recommended spare parts list with each machine. Parts can be ordered directly from our after-sales team.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Technical – Operations', question: 'The machine stops mid-run and shows an error. What should I do?', answer: 'Check the PLC touch screen for the error code and alarm message. The operation manual contains a full error code reference. Common causes: film break (check tension and splice), servo fault (check drive indicator lights), temperature alarm (verify heating element and thermocouple). If you cannot resolve the issue, contact Rey Long technical support with the error code and a description of the situation.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Technical – Operations', question: 'Can I run the machine at maximum speed immediately after startup?', answer: 'No. It is recommended to warm up the sealing bars for 10–15 minutes before running at full speed, allowing the temperature to stabilize uniformly across all heating groups. Start at low speed, verify seal quality, then gradually increase to target speed.', related_product: 'JL-L-2TZP600', priority: 'M' },
  { category: 'Technical – Operations', question: 'How do I adjust the zipper insertion position on zipper bags?', answer: 'Zipper position is adjusted via the servo-controlled zipper feeding mechanism on the PLC interface. Set the target zipper-to-top-seal distance, then run a test bag and measure. Fine-tune in small increments. The commissioning engineer covers zipper setup in detail during training.', related_product: 'JL-L-2TZP600', priority: 'M' },
  { category: 'Technical – Operations', question: 'What film roll width and core diameter does the machine accept?', answer: 'Max web roll diameter is φ600 mm. The machine accepts standard 3-inch cores. Max web width for the main film is 1240 mm; patch web is 150 mm. Please confirm your roll specifications when ordering to ensure the unwind stand is configured correctly.', related_product: 'JL-L-2TZP600', priority: 'M' },
  { category: 'Technical – Operations', question: 'Can the machine handle pre-printed films with registration marks?', answer: 'Yes. The JL-L-2TZP600 uses photo-eye registration sensors to track print marks on pre-printed films and maintain ≤0.3 mm positional accuracy. Ensure your film has a consistent, high-contrast registration mark and inform us of the mark position when configuring the machine.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Technical – Operations', question: 'What happens if the film breaks during production?', answer: 'The machine automatically stops and triggers a film break alarm. Resplice the film, re-thread through the film path, reset the alarm on the PLC, and restart at low speed to verify the splice seals correctly before returning to full production speed.', related_product: 'JL-L-2TZP600', priority: 'M' },
  { category: 'Technical – Operations', question: 'Is it possible to produce bags longer than 420 mm?', answer: 'Yes. The skip function allows bag lengths beyond the standard 420 mm limit, extending effective length up to 6× the base pitch. Contact our engineering team with your target dimensions for configuration confirmation.', related_product: 'JL-L-2TZP600', priority: 'M' },

  // Technical – Recycling (expanded)
  { category: 'Technical – Recycling', question: 'How does an eddy current separator actually work?', answer: 'The JLECS-1000W uses a high-speed rotating magnetic rotor inside a conveyor drum. As non-ferrous metal pieces (aluminum, copper) pass over the drum, the changing magnetic field induces eddy currents inside them, generating a repulsive force that launches them forward — away from non-conductive plastics and glass. The separation distance is controlled by belt speed and rotor frequency.', related_product: 'JLECS-1000W', priority: 'H' },
  { category: 'Technical – Recycling', question: 'What input material size does the JLECS-1000W accept?', answer: 'The JLECS-1000W is designed for pre-shredded or granulated material. Optimal particle size is roughly 5–80 mm — pieces smaller than 5 mm may not generate sufficient eddy current force for reliable separation. Contact our engineering team if your feed material is outside this range so we can recommend the correct screen or shredder setup upstream.', related_product: 'JLECS-1000W', priority: 'H' },
  { category: 'Technical – Recycling', question: 'Can the eddy current separator handle wet or damp material?', answer: 'Moisture reduces separation efficiency because water on the surface of metal particles can cause them to stick to non-metallic pieces and interfere with the repulsion trajectory. It is recommended to dry or air-separate the feed material before processing. Contact our engineering team for guidance on integrating a drying stage into your line.', related_product: 'JLECS-1000W', priority: 'M' },
  { category: 'Technical – Recycling', question: 'What ferrous removal stage is included with the JLECS-1000W?', answer: 'The JLECS-1000W includes a magnetic drum separator at the feed stage that removes ferrous metals (iron, steel) before the eddy current stage. Removing ferrous metals first protects the eddy current rotor and improves non-ferrous separation purity. Both stages operate in a continuous, single-pass process.', related_product: 'JLECS-1000W', priority: 'M' },
  { category: 'Technical – Recycling', question: 'What power and space do I need to install the JLECS-1000W?', answer: 'The JLECS-1000W is an industrial conveyor-based system. Specific power requirements and floor footprint depend on belt width and feed configuration. Please contact our engineering team with your production capacity target and available space — we will provide a full installation layout and electrical specification.', related_product: 'JLECS-1000W', priority: 'M' },
  { category: 'Technical – Recycling', question: 'What industries use eddy current separators?', answer: 'Common industries include plastic recycling (recovering aluminum caps, foil, and wire from plastic scrap), municipal solid waste (MSW) processing, electronic waste (e-waste) recycling, automotive shredder residue (ASR) processing, and glass cullet cleaning. The JLECS-1000W is suited for any stream containing mixed non-ferrous metals and non-conductive materials.', related_product: 'JLECS-1000W', priority: 'M' },

  // Technical – Printing Machine (expanded)
  { category: 'Technical – Printing Machine', question: 'What ink types does the flexographic printing machine use?', answer: 'The JLRPM-6800BO/6C is compatible with water-based inks commonly used for PP woven fabric printing. Water-based inks provide good adhesion on PP surfaces and comply with environmental regulations in most markets. Solvent-based ink compatibility should be confirmed with our engineering team based on your specific substrate and end-use requirements.', related_product: 'JLRPM-6800BO/6C', priority: 'H' },
  { category: 'Technical – Printing Machine', question: 'What is the print repeat range on the JLRPM-6800BO/6C?', answer: 'The JLRPM-6800BO/6C supports a print repeat range of 450–1200 mm, allowing a wide variety of bag and fabric repeat patterns. The repeat is determined by the anilox roller circumference — contact our team with your target repeat length when ordering printing cylinders.', related_product: 'JLRPM-6800BO/6C', priority: 'M' },
  { category: 'Technical – Printing Machine', question: 'How accurate is the color-to-color registration on the flexographic printer?', answer: 'The JLRPM-6800BO/6C uses servo-driven print stations with inter-station tension control and register correction, delivering consistent color-to-color registration. For the exact registration tolerance specification of your configuration, please contact our engineering team — performance depends on substrate type, ink viscosity, and print speed.', related_product: 'JLRPM-6800BO/6C', priority: 'H' },
  { category: 'Technical – Printing Machine', question: 'Can the printing machine print on both sides of the fabric?', answer: 'Yes. The JLRPM-6800BO/6C supports front/back printing in configurations 1+5, 2+4, and 3+3 (front + back color distribution). This allows simultaneous double-sided printing in a single pass, which is common for PP woven bags requiring exterior branding and interior text.', related_product: 'JLRPM-6800BO/6C', priority: 'M' },
  { category: 'Technical – Printing Machine', question: 'What is the maximum web width the flexographic printer handles?', answer: 'The JLRPM-6800BO/6C handles a maximum web width of 800 mm, at a maximum machine speed of 120 m/min (printing speed up to 100 m/min). This covers the full width range required for standard PP woven bag fabric produced by most circular looms.', related_product: 'JLRPM-6800BO/6C', priority: 'M' },
  { category: 'Technical – Printing Machine', question: 'Does the flexographic printer include a drying system?', answer: 'Yes. The JLRPM-6800BO/6C includes an inter-color drying system between each print station to ensure ink is dry before the next color is applied. This prevents color bleeding and maintains print sharpness at high speeds. Contact us for details on the drying method (hot air or IR) applicable to your ink and substrate.', related_product: 'JLRPM-6800BO/6C', priority: 'M' },

  // Technical – JLPTCSM-1300W (expanded)
  { category: 'Technical – JLPTCSM-1300W', question: 'What type of sewing thread is used on the PP woven bag convention line?', answer: 'The JLPTCSM-1300W uses industrial sewing thread appropriate for PP woven bag construction — typically polyester or polypropylene thread. Thread specification (weight, twist) affects seam strength and should be matched to the fabric weight and load capacity of the finished bag. Contact our engineering team with your bag load rating for a thread recommendation.', related_product: 'JLPTCSM-1300W', priority: 'M' },
  { category: 'Technical – JLPTCSM-1300W', question: 'What fabric tensile strength does the JLPTCSM-1300W require?', answer: 'The JLPTCSM-1300W is designed to process standard PP woven fabric produced by circular looms. Fabric tensile strength requirements depend on the sewing tension settings. Contact our engineering team with your fabric weight (gsm) and warp/weft count — we will advise on tension settings to avoid fabric damage during tubing and cutting.', related_product: 'JLPTCSM-1300W', priority: 'M' },
  { category: 'Technical – JLPTCSM-1300W', question: 'Can the PP woven bag line integrate with a downstream filling machine?', answer: 'The JLPTCSM-1300W produces finished, sewn, and taped PP woven bags ready for filling. Integration with downstream filling equipment depends on the bag opening format (top-open or valve bag) and conveyor interface. Contact our engineering team and provide details of your filling machine for a compatibility assessment.', related_product: 'JLPTCSM-1300W', priority: 'M' },
  { category: 'Technical – JLPTCSM-1300W', question: 'What is the power requirement for the JLPTCSM-1300W convention line?', answer: 'The JLPTCSM-1300W is an integrated line spanning four production stages — printing, tubing, cutting/sewing, and overtape. Total power consumption depends on the full line configuration. Please contact us with your production specifications and local power standard for a complete electrical requirement sheet.', related_product: 'JLPTCSM-1300W', priority: 'M' },
  { category: 'Technical – JLPTCSM-1300W', question: 'Can the convention line produce laminated PP woven bags?', answer: 'The JLPTCSM-1300W is designed to process both plain and laminated PP woven fabric. BOPP laminated fabric is commonly used when moisture resistance or a glossy print surface is required. Confirm your fabric type (plain or laminated) when ordering to ensure the tubing and sewing sections are configured for the correct thickness and stiffness.', related_product: 'JLPTCSM-1300W', priority: 'M' },

  // AI Solutions (expanded)
  { category: 'AI Solutions', question: 'What specific inspection tasks can the AI vision system perform?', answer: "Rey Long's AI Machine Intelligence vision system can be configured for tasks such as surface defect detection (holes, stains, mis-weave on PP fabric), seal integrity verification on finished bags, print registration inspection, and foreign object detection. The specific inspection tasks are defined case-by-case based on your production line and quality requirements.", related_product: 'AI Solutions', priority: 'H' },
  { category: 'AI Solutions', question: 'What hardware is required to install the AI Machine Intelligence system?', answer: "The system is built on edge computing hardware (industrial PC or embedded AI accelerator) installed at the machine. Required hardware typically includes industrial cameras, sensors, and an edge computing unit — all selected based on your inspection task and machine speed. Rey Long handles hardware selection and integration as part of the project scope. No cloud server or internet connection is required for real-time operation.", related_product: 'AI Solutions', priority: 'H' },
  { category: 'AI Solutions', question: 'How long does it take to deploy the AI Machine Intelligence system?', answer: "Deployment timeline depends on the complexity of the inspection task and the condition of the existing machine. A typical project involves an initial assessment, custom model training, hardware installation, and on-site validation. Contact our team with your machine model and target application — we will provide a project timeline estimate.", related_product: 'AI Solutions', priority: 'M' },
  { category: 'AI Solutions', question: 'Does the AI system require internet connectivity to operate?', answer: "No. Rey Long's AI Machine Intelligence runs entirely on edge computing hardware installed at the machine. All inference and decision-making happens locally in real time, with no dependency on cloud connectivity. This is critical for factory environments where network availability may be limited or where data security is a concern.", related_product: 'AI Solutions', priority: 'M' },
  { category: 'AI Solutions', question: 'Can predictive maintenance detect problems before a machine breakdown?', answer: "Yes. The predictive maintenance module analyzes sensor data (vibration, temperature, motor current) in real time to identify abnormal patterns that precede failures — such as bearing wear, belt elongation, or heating element degradation. The system generates early warnings so maintenance can be scheduled during planned downtime, reducing unplanned stops. Contact us to discuss sensor integration for your specific machine.", related_product: 'AI Solutions', priority: 'H' },

  // Technical – JL-L-2TZP600 (film change / QC)
  { category: 'Technical – JL-L-2TZP600', question: 'What should I check when switching to a new film material on the JL-L-2TZP600?', answer: "When switching film materials, adjust: (1) sealing temperature — set based on the new film's heat-seal layer specification, (2) sealing dwell time if running at high speed, (3) film tension to match the new film's stiffness, (4) photo-eye sensitivity if the registration mark color or contrast changes. Run at low speed with the new material and inspect seal quality and bag dimensions before returning to full production speed.", related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Technical – JL-L-2TZP600', question: 'How do I calculate the output efficiency of the JL-L-2TZP600?', answer: 'Effective output (bags/hour) = machine speed (pcs/min) × 60 × availability rate. Availability rate accounts for planned stops (film splicing, maintenance) and unplanned downtime. At 120 pcs/min with 85% availability, the effective output is approximately 6,120 bags/hour. For detailed OEE (Overall Equipment Effectiveness) benchmarking for your production target, contact our engineering team.', related_product: 'JL-L-2TZP600', priority: 'M' },
  { category: 'Technical – JL-L-2TZP600', question: 'What quality standards apply to bags produced by the JL-L-2TZP600?', answer: 'Bags produced by the JL-L-2TZP600 can be manufactured to meet customer-specified quality standards. Common references include ASTM F88 (seal strength test) and ISO 15223 for medical packaging. The machine itself provides ≤0.3 mm positional accuracy and consistent sealing via PLC control. For industry-specific certification requirements, please discuss your end-use application with our engineering team.', related_product: 'JL-L-2TZP600', priority: 'M' },

  // Procurement / Business (expanded)
  { category: 'Procurement', question: 'Can I visit the Rey Long factory before placing an order?', answer: 'Yes. Factory visits are welcome — please contact us to schedule a visit with advance notice. During your visit you can inspect machines in production, discuss specifications with our engineers, and in some cases observe a live demonstration on machines currently in production or under test. Please reach out via our Contact page to arrange a visit date.', related_product: 'All', priority: 'H' },
  { category: 'Procurement', question: 'Is there a minimum order quantity for machines?', answer: 'Machines are sold individually — there is no minimum quantity requirement. Whether you need one machine or multiple units for a new production line, our team can provide a quotation. Volume orders may be eligible for preferential pricing — please contact us for details.', related_product: 'All', priority: 'H' },
  { category: 'Procurement', question: 'Do you offer leasing or financing options for machinery?', answer: 'Leasing and financing arrangements are not directly provided by Rey Long but may be available through third-party financial institutions in your region. We can provide the necessary documentation (invoice, machine specifications, company registration) to support your financing application. Please contact us to discuss what documentation you need.', related_product: 'All', priority: 'M' },

  // Sealing Technology – from technical papers
  { category: 'Sealing Technology', question: 'What is the heat-seal window and why does it matter?', answer: 'The heat-seal window is the narrow temperature range where a film fuses correctly — above it, the laminate burns or sticks to the sealing jaws; below it, the seal fails to bond. As eco-friendly mono-material films become more common, this window becomes extremely narrow, making precise temperature control critical for consistent seal quality.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Sealing Technology', question: 'Why does the JL-L-2TZP600 use multi-stage progressive heating instead of a single heating station?', answer: 'Progressive heating divides the sealing process across 8–20 independent heating blocks, each applying a brief "instant" press. This accumulates thermal energy gradually, allowing deep heat penetration into thick areas (corners, gussets) without burning the thinner film layers — all while maintaining speeds up to 220 pcs/min. A single station would require slowing down the line to achieve the same dwell time.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Sealing Technology', question: 'What are the three variables that control heat seal quality?', answer: 'The three critical variables are: (1) Temperature — controlled up to 300°C via PID controllers and Solid State Relays (SSR) with 2-second feedback loops; (2) Dwell time — how long the sealing jaws remain in contact with the film; (3) Pressure — the mechanical clamping force applied to fuse the layers. All three are adjusted via the PLC touch-screen HMI.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Sealing Technology', question: 'Why must zippers be sealed with ultrasonic technology rather than heat sealing?', answer: 'A plastic zipper has far greater thermal mass than the surrounding 30–180 μm film. If external heat is used to melt the zipper, the thin film burns away before the zipper reaches fusion temperature. Ultrasonic technology generates heat internally through high-frequency molecular friction only at the zipper-to-film interface, bonding the zipper without damaging the surrounding bag material.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Sealing Technology', question: 'What is the difference between sealing a gusset and sealing a zipper?', answer: 'A gusset is simply multiple layers of the same film material folded together — it is handled with heat sealing by extending dwell time or reducing speed to allow heat to penetrate. A zipper is a different material entirely (solid plastic strip) with much higher thermal mass, requiring ultrasonic vibration for precise interface bonding. Applying heat sealing to a zipper would destroy the surrounding film.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Sealing Technology', question: 'What are common heat sealing defects and their causes?', answer: 'The four main defects are: (1) Thermal shrinkage/wrinkling — excessive heat on thin film areas causes contraction; (2) Burn-through/melting — temperature exceeds the seal window, laminate sticks to jaws; (3) Weak seals/leakage — insufficient heat penetration in thick overlap areas such as four-side seal corners; (4) Stretching and breakage — overheated material loses structural tension and tears under motor pull.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Sealing Technology', question: 'What is the role of the cooling bar in the JL-L-2TZP600?', answer: 'After sealing, the film is soft and vulnerable to stretching or warping at high speed. Cooling bars (water-cooled plates at 15–20°C) act as a thermal brake immediately after the sealing stations: they instantly solidify the fused plastic to achieve full seal strength, prevent residual heat from warping the bag, and allow the film to withstand the tension of high-speed servo motors pulling at up to 220 pcs/min.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Sealing Technology', question: 'How does zoned temperature control work on the JL-L-2TZP600?', answer: 'Up to 20 independent heating blocks are individually controlled via the PLC-managed HMI. Each block can apply a specific temperature to a precise coordinate of the bag, allowing the machine to deliver high heat to thick gusset corners while applying lower heat to thin film areas in the same cycle. This prevents burn-through on thin sections while ensuring full fusion at thick overlap points.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Sealing Technology', question: 'What is Edge Position Control (EPC) and how does it maintain print alignment?', answer: 'EPC is an automated film guidance system that uses a CCD camera combined with photoelectric sensors to track registration marks and film edges in real-time. When tension changes cause the film to drift, the system instantly triggers correction motors to re-center the film path — maintaining positional accuracy within ≤0.3 mm without stopping the line. This is essential for pre-printed films at 220 pcs/min.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Sealing Technology', question: 'Can the JL-L-2TZP600 handle eco-friendly mono-material films?', answer: 'Yes. Mono-material films (such as all-PE or all-PP structures) have a narrower heat-seal window than traditional multi-layer laminates. The JL-L-2TZP600 is equipped to handle these materials through its zoned independent temperature control, PID/SSR feedback every 2 seconds, and progressive multi-stage heating — all of which provide the precision needed to stay within the narrow sealing window without burn-through.', related_product: 'JL-L-2TZP600', priority: 'H' },
  { category: 'Sealing Technology', question: 'How does the number of heating blocks affect production speed for complex bags?', answer: 'More heating blocks allow higher production speeds for complex bags. Machines with 20 blocks maintain approximately 120 pcs/min on four-side seal bags by accumulating heat progressively across stations — a roughly 20% efficiency gain over machines with fewer blocks that must slow to 100 pcs/min to achieve the same seal penetration. The multi-stage approach avoids sacrificing speed to satisfy the thickest part of the bag.', related_product: 'JL-L-2TZP600', priority: 'M' },
  { category: 'Sealing Technology', question: 'How is sealing temperature monitored and adjusted on the machine?', answer: 'Temperature is managed through PID (Proportional-Integral-Derivative) controllers and Solid State Relays (SSR), which provide a closed-loop feedback cycle every 2 seconds. Operators monitor and adjust all temperature zones in real-time via the 10-inch full-color HMI touch screen. No hardware changes are required — adjustments are made digitally while the machine is running.', related_product: 'JL-L-2TZP600', priority: 'M' },
]

export const GET: APIRoute = async ({ request, locals }) => {
  const env = (locals as any)?.runtime?.env ?? {}
  const ai = env.AI as { run: (model: string, opts: Record<string, unknown>) => Promise<unknown> } | undefined
  const seedSecret: string = env.SEED_SECRET ?? import.meta.env.SEED_SECRET ?? ''

  const url = new URL(request.url)
  const key = url.searchParams.get('key')

  if (!seedSecret || key !== seedSecret) {
    return new Response(JSON.stringify({ error: 'Unauthorized' }), {
      status: 401,
      headers: { 'Content-Type': 'application/json' },
    })
  }

  if (!ai) {
    return new Response(JSON.stringify({ error: 'AI binding not configured' }), {
      status: 503,
      headers: { 'Content-Type': 'application/json' },
    })
  }

  const supabaseUrl: string = env.SUPABASE_URL ?? import.meta.env.SUPABASE_URL ?? ''
  const supabaseServiceKey: string = env.SUPABASE_SERVICE_ROLE_KEY ?? import.meta.env.SUPABASE_SERVICE_ROLE_KEY ?? ''

  if (!supabaseUrl || !supabaseServiceKey) {
    return new Response(JSON.stringify({ error: 'Supabase env vars not configured' }), {
      status: 503,
      headers: { 'Content-Type': 'application/json' },
    })
  }

  try {
    const BATCH = 20
    type Row = QAEntry & { embedding: number[] }
    const rows: Row[] = []

    // Generate embeddings in batches
    for (let i = 0; i < QA.length; i += BATCH) {
      const batch = QA.slice(i, i + BATCH)
      const texts = batch.map(q => q.question)
      const result = await ai.run('@cf/baai/bge-small-en-v1.5', { text: texts }) as { data: number[][] }
      for (let j = 0; j < batch.length; j++) {
        rows.push({ ...batch[j], embedding: result.data[j] })
      }
    }

    // Insert in batches
    let inserted = 0
    for (let i = 0; i < rows.length; i += BATCH) {
      const batch = rows.slice(i, i + BATCH)
      const res = await fetch(`${supabaseUrl}/rest/v1/chatbot_qa`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          apikey: supabaseServiceKey,
          Authorization: `Bearer ${supabaseServiceKey}`,
          Prefer: 'return=minimal',
        },
        body: JSON.stringify(batch),
      })
      if (!res.ok) {
        const err = await res.text()
        return new Response(JSON.stringify({ error: `Insert failed at row ${i}: ${err}` }), {
          status: 500,
          headers: { 'Content-Type': 'application/json' },
        })
      }
      inserted += batch.length
    }

    return new Response(JSON.stringify({ success: true, inserted, total: QA.length }), {
      headers: { 'Content-Type': 'application/json' },
    })
  } catch (err) {
    console.error('[seed] error:', err)
    return new Response(JSON.stringify({ error: String(err) }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    })
  }
}
