import openpyxl, sys, io
from openpyxl.styles import PatternFill

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

wb = openpyxl.load_workbook(r'C:\dev\marketing strategy\reylong-leads\output\leads.xlsx')
ws = wb['買主名單']
headers = [cell.value for cell in ws[1]]

new_leads = [
    {
        '公司名稱': 'Reynolds Consumer Products (Ziploc) - Ziplock Bag Manufacturer',
        '國家': 'US',
        '產品描述': 'Reynolds Consumer Products makes Ziploc, the leading U.S. brand of slider and press-to-close ziplock storage bags. Based in Appleton, WI. Ranked #12 in Slider Ziplock Bag Making Machine importers. Massive annual volume of zipper bags, directly aligned with JL-L-2TZP600 zipper bag capability.',
        '官方網址': 'reynoldsconsumerproducts.com',
        '聯絡頁面': None,
        '來源平台': 'Dee Machine Importers / Slider Ziplock',
        '優先級': '⭐ 高優先',
        '標記關鍵字': 'zipper bag,slider,high volume,consumer',
        '開發': None,
        '草稿狀態': '待生成',
        '最後聯繫日期': None,
    },
    {
        '公司名稱': 'Amcor Flexibles North America - Flexible Packaging',
        '國家': 'US',
        '產品描述': 'Amcor Flexibles North America is one of the largest flexible packaging companies globally, based in Deerfield, IL. Appears in Side Sealing (#10), Slider Ziplock (#11), and Grape Bag (#11) machine importer lists. Produces medical and food-grade high-speed bags including three-side seal and Doypack pouches.',
        '官方網址': 'amcor.com',
        '聯絡頁面': None,
        '來源平台': 'Dee Machine Importers / Side Sealing + Slider Ziplock',
        '優先級': '⭐ 高優先',
        '標記關鍵字': 'three-side seal,doypack,food,medical,flexible packaging',
        '開發': None,
        '草稿狀態': '待生成',
        '最後聯繫日期': None,
    },
    {
        '公司名稱': 'Coveris Flexibles US - Performance Packaging',
        '國家': 'US',
        '產品描述': 'Coveris Flexibles US is a Chicago-based performance packaging company specializing in multi-lane side-sealing flexible packaging. Ranked #16 in Side Sealing Bag importer list. Directly aligned with JL-L-2TZP600 three-side seal capability.',
        '官方網址': 'coveris.com',
        '聯絡頁面': None,
        '來源平台': 'Dee Machine Importers / Side Sealing',
        '優先級': '⭐ 高優先',
        '標記關鍵字': 'side seal,three-side seal,performance packaging',
        '開發': None,
        '草稿狀態': '待生成',
        '最後聯繫日期': None,
    },
    {
        '公司名稱': 'Winpak Ltd. - High-Barrier Food Packaging',
        '國家': 'US',
        '產品描述': 'Winpak Ltd. is a high-barrier film and packaging manufacturer serving the US Midwest market. Ranked in both Side Sealing (#19) and Slider Ziplock (#19) importer lists. Specializes in heat-seal laminated films matching JL-L-2TZP600 material spec (30-180 um heat-seal laminated film).',
        '官方網址': 'winpak.com',
        '聯絡頁面': None,
        '來源平台': 'Dee Machine Importers / Side Sealing + Slider Ziplock',
        '優先級': '⭐ 高優先',
        '標記關鍵字': 'high-barrier,heat-seal,food packaging,zipper',
        '開發': None,
        '草稿狀態': '待生成',
        '最後聯繫日期': None,
    },
    {
        '公司名稱': 'Printpack Inc. - Flexible Packaging Atlanta',
        '國家': 'US',
        '產品描述': 'Printpack Inc. is an Atlanta, GA-based advanced flexible packaging company. Appears in Side Sealing (#20), Slider Ziplock (#20), and Grape Bag (#20) machine importer lists. Specializes in registered-print poly bag converting including three-side seal and zipper formats.',
        '官方網址': 'printpack.com',
        '聯絡頁面': None,
        '來源平台': 'Dee Machine Importers / Side Sealing + Slider Ziplock + Grape Bag',
        '優先級': '⭐ 高優先',
        '標記關鍵字': 'three-side seal,zipper,doypack,printed flexible packaging',
        '開發': None,
        '草稿狀態': '待生成',
        '最後聯繫日期': None,
    },
    {
        '公司名稱': 'Novolex - Retail and Industrial Bag Manufacturer',
        '國家': 'US',
        '產品描述': 'Novolex (Hartsville, SC) is a major retail and industrial bag converter appearing in Side Sealing (#17) and Slider Ziplock (#16) importer lists. Operates continuous-motion side-weld equipment for deli and grocery-grade slider/zipper bags.',
        '官方網址': 'novolex.com',
        '聯絡頁面': None,
        '來源平台': 'Dee Machine Importers / Side Sealing + Slider Ziplock',
        '優先級': '⭐ 高優先',
        '標記關鍵字': 'side seal,zipper,retail bag,industrial',
        '開發': None,
        '草稿狀態': '待生成',
        '最後聯繫日期': None,
    },
    {
        '公司名稱': 'Sonoco Products Company - Flexible Packaging',
        '國家': 'US',
        '產品描述': 'Sonoco Products Company (Hartsville, SC) is a diversified industrial and flexible packaging company. Appears in Side Sealing (#12), Slider Ziplock (#18), and Grape Bag (#19) importer lists. Produces flexible packaging and pouches across food, consumer, and industrial sectors.',
        '官方網址': 'sonoco.com',
        '聯絡頁面': None,
        '來源平台': 'Dee Machine Importers / Side Sealing + Slider Ziplock + Grape Bag',
        '優先級': '⭐ 高優先',
        '標記關鍵字': 'flexible packaging,pouch,three-side seal,industrial',
        '開發': None,
        '草稿狀態': '待生成',
        '最後聯繫日期': None,
    },
    {
        '公司名稱': 'Sealed Air Corporation - Food and Protective Packaging',
        '國家': 'US',
        '產品描述': 'Sealed Air Corporation (Charlotte, NC), maker of Cryovac brand. Ranked in Side Sealing (#13) and Slider Ziplock (#13) importer lists. Produces protective packaging, bubble packaging, and fresh food packaging with ziplock systems.',
        '官方網址': 'sealedair.com',
        '聯絡頁面': None,
        '來源平台': 'Dee Machine Importers / Side Sealing + Slider Ziplock',
        '優先級': '⭐ 高優先',
        '標記關鍵字': 'side seal,zipper,food packaging,protective',
        '開發': None,
        '草稿狀態': '待生成',
        '最後聯繫日期': None,
    },
    {
        '公司名稱': 'TC Transcontinental Packaging - Consumer Flexible Packaging',
        '國家': 'US',
        '產品描述': 'TC Transcontinental Packaging (Chicago, IL) is a consumer-facing flexible packaging company appearing in Side Sealing (#18), Slider Ziplock (#17), and Grape Bag (#17) importer lists. Produces side-seal bags and slider-zipper lines for pet food, consumer goods, and fresh produce.',
        '官方網址': 'tctranscontinental.com',
        '聯絡頁面': None,
        '來源平台': 'Dee Machine Importers / Side Sealing + Slider Ziplock + Grape Bag',
        '優先級': '⭐ 高優先',
        '標記關鍵字': 'side seal,zipper,consumer packaging,pet food',
        '開發': None,
        '草稿狀態': '待生成',
        '最後聯繫日期': None,
    },
    {
        '公司名稱': 'Emerald Packaging Inc. - Agricultural Flexible Packaging',
        '國家': 'US',
        '產品描述': 'Emerald Packaging, Inc. (Union City, CA) is a major West Coast agricultural packaging converter ranked #9 in Grape Bag machine importer list. Imports high-speed slider-zipper produce bag lines. Strong niche fit for JL-L-2TZP600 zipper bag production.',
        '官方網址': 'emeraldpkg.com',
        '聯絡頁面': None,
        '來源平台': 'Dee Machine Importers / Grape Bag Slider Zipper',
        '優先級': '⭐ 高優先',
        '標記關鍵字': 'zipper,agricultural,produce bag,West Coast',
        '開發': None,
        '草稿狀態': '待生成',
        '最後聯繫日期': None,
    },
    {
        '公司名稱': 'Berry Global Inc. - Industrial Flexible Packaging',
        '國家': 'US',
        '產品描述': 'Berry Global, Inc. (Evansville, IN) is one of the largest industrial plastic film and bag manufacturers in the US. Appears in Side Sealing (#11), Slider Ziplock (#10), and Grape Bag (#10) importer lists. Primarily industrial-scale; high entry barrier but significant long-term potential.',
        '官方網址': 'berryglobal.com',
        '聯絡頁面': None,
        '來源平台': 'Dee Machine Importers / Side Sealing + Slider Ziplock + Grape Bag',
        '優先級': 'normal',
        '標記關鍵字': 'industrial,plastic film,slider,side seal',
        '開發': None,
        '草稿狀態': '待生成',
        '最後聯繫日期': None,
    },
    {
        '公司名稱': 'Sigma Plastics Group - PE Film and Bag Manufacturing',
        '國家': 'US',
        '產品描述': 'Sigma Plastics Group (Pompano Beach, FL) is a leading private PE film extruder appearing in Side Sealing (#15), Slider Ziplock (#15), and Grape Bag (#13) importer lists. Primarily PE film bags with partial overlap for JL-L-2TZP600 slider bag capability.',
        '官方網址': 'sigmaplastics.com',
        '聯絡頁面': None,
        '來源平台': 'Dee Machine Importers / Side Sealing + Slider Ziplock + Grape Bag',
        '優先級': 'normal',
        '標記關鍵字': 'PE film,plastic bag,slider',
        '開發': None,
        '草稿狀態': '待生成',
        '最後聯繫日期': None,
    },
    {
        '公司名稱': 'Volm Companies Inc. - Fresh Produce Packaging Distributor',
        '國家': 'US',
        '產品描述': 'Volm Companies, Inc. (Antigo, WI) is a major fresh produce packaging distributor ranked #12 in Grape Bag machine importer list. Imports specialized converting equipment for agricultural accounts. Niche fit for zipper produce bag production.',
        '官方網址': 'volmcompanies.com',
        '聯絡頁面': None,
        '來源平台': 'Dee Machine Importers / Grape Bag Slider Zipper',
        '優先級': 'normal',
        '標記關鍵字': 'produce,agricultural,zipper bag',
        '開發': None,
        '草稿狀態': '待生成',
        '最後聯繫日期': None,
    },
    {
        '公司名稱': 'Sun World International - Branded Grape Packaging',
        '國家': 'US',
        '產品描述': 'Sun World International / Diversified Partners (Palm Desert, CA) is a branded grape grower and packer ranked #14 in Grape Bag importer list. Directly imports automated slider-bagging equipment for proprietary branded grape packaging.',
        '官方網址': 'sunworld.com',
        '聯絡頁面': None,
        '來源平台': 'Dee Machine Importers / Grape Bag Slider Zipper',
        '優先級': 'normal',
        '標記關鍵字': 'grape,zipper bag,produce',
        '開發': None,
        '草稿狀態': '待生成',
        '最後聯繫日期': None,
    },
    {
        '公司名稱': 'Jakov Dulcich and Sons (Pretty Lady Vineyards)',
        '國家': 'US',
        '產品描述': 'Jakov Dulcich and Sons dba Pretty Lady Vineyards (Delano, CA) is a major Central Valley grape grower and packer ranked #15 in Grape Bag importer list. Imports automated inline slider-bagging equipment for fresh grape packaging at scale.',
        '官方網址': 'prettyladygrapes.com',
        '聯絡頁面': None,
        '來源平台': 'Dee Machine Importers / Grape Bag Slider Zipper',
        '優先級': 'normal',
        '標記關鍵字': 'grape,zipper bag,produce,California',
        '開發': None,
        '草稿狀態': '待生成',
        '最後聯繫日期': None,
    },
    {
        '公司名稱': 'Novolex Shields Bag and Printing - West Coast Agricultural Bags',
        '國家': 'US',
        '產品描述': 'Novolex subsidiary Shields Bag and Printing (Yakima, WA) specializes in West Coast agricultural and personal-care bag manufacturing. Ranked #18 in Grape Bag importer list. Handles vented slider poly profiles for fresh produce markets.',
        '官方網址': 'novolex.com',
        '聯絡頁面': None,
        '來源平台': 'Dee Machine Importers / Grape Bag Slider Zipper',
        '優先級': 'normal',
        '標記關鍵字': 'zipper,agricultural,West Coast,produce bag',
        '開發': None,
        '草稿狀態': '待生成',
        '最後聯繫日期': None,
    },
]

green_fill = PatternFill('solid', fgColor='E2EFDA')
yellow_fill = PatternFill('solid', fgColor='FFF2CC')

for lead in new_leads:
    row_values = [lead.get(h) for h in headers]
    ws.append(row_values)
    fill = green_fill if '高優先' in str(lead.get('優先級', '')) else yellow_fill
    for col in range(1, len(headers) + 1):
        ws.cell(row=ws.max_row, column=col).fill = fill

wb.save(r'C:\dev\marketing strategy\reylong-leads\output\leads.xlsx')
print(f'新增 {len(new_leads)} 筆，現在共 {ws.max_row - 1} 筆')
high = sum(1 for l in new_leads if '高優先' in str(l.get('優先級', '')))
print(f'  高優先: {high} 筆（綠色）')
print(f'  一般: {len(new_leads) - high} 筆（黃色）')
